-- ============================================================
-- TRANSLATION RULES SEED — from production (192.95.36.154)
-- Loads ALL translation rules (SMPP/HTTP/VoiceOTP SID, number,
-- content, OTP extract, blacklist/whitelist). Regenerate via:
--   pg_dump -h localhost -U sms_user -d sms_platform --data-only --column-inserts -t translations
-- ============================================================
TRUNCATE translations RESTART IDENTITY;


INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (89, 'otp_extract', '', '', NULL, NULL, NULL, true, '2026-07-14 16:12:17.096283', 'Bank OTP', 'Extract 6-digit OTP and send clean code', '', 3, 'supplier', '73', NULL, NULL, 0, '', '', '{{OTP}}', true, 4, 8, '[]', 'exact', '{}', NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (88, 'otp_extract', '', '', NULL, NULL, NULL, true, '2026-07-14 16:12:17.094929', 'Extract OTP Only', 'Extract 4-8 digit code and forward only OTP number', '', 1, 'supplier', '63', NULL, NULL, 0, '', '', '{{OTP}}', true, 4, 8, '[]', 'exact', '{}', NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (112, 'number_blacklist', '251', '', NULL, NULL, NULL, true, '2026-08-10 05:56:12.550141', 'Block Ethiopia (+251)', 'Reject all SMS destined to Ethiopia numbers (prefix 251).', 'prefix', 1, 'both', 'all', NULL, NULL, 0, '', '', '', false, 4, 8, '[]', 'exact', '{}', NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (113, 'number_blacklist', '00251', '', NULL, NULL, NULL, true, '2026-08-10 05:56:12.553875', 'Block Ethiopia (00251)', 'Reject all SMS destined to Ethiopia numbers in 00251 format.', 'prefix', 1, 'both', 'all', NULL, NULL, 0, '', '', '', false, 4, 8, '[]', 'exact', '{}', NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (92, 'sid_alias', 'SPAM*', 'INFO', NULL, NULL, NULL, true, '2026-07-14 16:12:17.099809', 'Mask SPAM', 'Replace SPAM* senders with INFO', '', 2, 'both', 'all', NULL, NULL, 0, '', '', '', false, 4, 8, '[]', 'wildcard', '{}', NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (87, 'content_replace', '', '', NULL, NULL, NULL, false, '2026-07-14 16:12:17.093635', 'Promo Replace', 'Replace promo text with branded message', '', 2, 'both', 'all', NULL, NULL, 0, '', 'SPECIAL OFFER', 'Net2App Special: {{OTP}}', true, 4, 8, '[]', 'exact', '{}', NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (90, 'sid_random', '', 'NET2APP|N2AHUB|SMSHUB|MSG2U|TXTNOW', NULL, NULL, NULL, true, '2026-07-14 16:12:17.097422', 'Net2App SID Pool', 'Random sender ID from pool for outbound SMS', '', 5, 'both', 'all', NULL, NULL, 0, '', '', '', false, 4, 8, '["NET2APP", "N2AHUB", "SMSHUB", "MSG2U", "TXTNOW"]', 'exact', '{}', NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (93, 'random_content', '', 'Your OTP code is {{OTP}}. Valid for 5 min.|Verification code: {{OTP}}|{{OTP}} is your one-time password|OTP: {{OTP}}. Do not share.', NULL, NULL, NULL, false, '2026-07-14 16:12:17.100993', 'OTP Templates Pool', 'Random OTP message templates — extracts OTP from original and wraps in random template', '', 1, 'both', 'all', NULL, NULL, 0, '', '', '', true, 4, 8, '["Your OTP code is {{OTP}}. Valid for 5 min.", "Verification code: {{OTP}}", "{{OTP}} is your one-time password", "OTP: {{OTP}}. Do not share."]', 'exact', '{}', NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (94, 'random_content', '', 'Flash Sale! 50% off today only|Limited time offer: {{OTP}} for discount|Special deal: use code {{OTP}}|Exclusive offer just for you!', NULL, NULL, NULL, false, '2026-07-14 16:12:17.102215', 'Promo Templates', 'Random promotional message templates', '', 2, 'both', 'all', NULL, NULL, 0, '', '', '', false, 4, 8, '["Flash Sale! 50% off today only", "Limited time offer: {{OTP}} for discount", "Special deal: use code {{OTP}}", "Exclusive offer just for you!"]', 'exact', '{}', NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (95, 'sid_random', '', 'BD-SID', NULL, NULL, NULL, false, '2026-07-14 16:33:05.955179', 'TEST: BD 47001 to BD-SID', '', '', 1, 'both', 'all', NULL, NULL, 0, '', '', '', false, 4, 8, '["BD-SID"]', 'exact', '{2412}', NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (91, 'sid_alias', '*', '8809606981402', NULL, NULL, NULL, false, '2026-07-14 16:12:17.098696', 'ALL', 'Replace any sender starting with TECHCORP to TC-MSG', '', 1, 'both', 'all', NULL, NULL, 0, '', '', '', false, 4, 8, '[]', 'wildcard', '{}', NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (86, 'content_replace', '', '', NULL, NULL, NULL, false, '2026-07-14 16:12:17.091928', 'OTP Forward (broad)', 'Extract OTP from "your code is" messages and forward in new format', '', 1, 'both', 'all', NULL, NULL, 0, '', 'code', 'Your OTP: {{OTP}}', true, 4, 8, '[]', 'exact', '{}', NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (96, 'number_prefix', '88', '', NULL, NULL, NULL, true, '2026-07-24 23:46:21.022055', 'Bangladesh (88)', '', '', 1, 'supplier', '63', NULL, NULL, 2, '', '', '', false, 4, 8, '[]', 'wildcard', NULL, NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (114, 'number_prefix', '00', '', NULL, NULL, NULL, true, '2026-08-14 00:00:00.000000', 'Strip 00 (00880→880, 0091→91)', 'Strip 00 prefix when client sends 00+country code; otherwise forward as-is', '', 1, 'both', 'all', NULL, NULL, 2, '', '', '', false, 4, 8, '[]', 'exact', NULL, NULL, true);
INSERT INTO public.translations (id, translation_type, source_pattern, target_value, client_id, supplier_id, route_id, is_active, created_at, name, description, subtype, priority, apply_to, apply_entity_id, mcc, mnc, strip_prefix_digits, add_prefix_text, match_content, replace_content, is_otp_extract, otp_length_min, otp_length_max, template_data, sid_match_type, mccmnc_list, otp_pattern, otp_strict_mode) VALUES (115, 'number_prefix', '0091', '', NULL, NULL, NULL, true, '2026-08-14 00:00:00.000000', 'India 0091', 'Strip 00 from 0091 numbers -> 91 (forward without 00)', '', 1, 'both', 'all', NULL, NULL, 2, '', '', '', false, 4, 8, '[]', 'exact', NULL, NULL, true);

-- Re-sync the id sequence so NEW rules created after seeding get higher ids
-- than the seeded ones (rules sort by priority ASC, id DESC -- newer rules win
-- within the same priority).
SELECT setval('translations_id_seq', (SELECT COALESCE(MAX(id), 1) FROM translations));
