import React, { useEffect, useRef, useState } from 'react';
import { Html5Qrcode } from 'html5-qrcode';
import { GatewayConfig } from '../services/GatewayContext';

/**
 * Pairing QR payload generated by the NET2APP server
 * (GET /api/suppliers/:id/pairing-qr).
 */
export interface PairingPayload {
  v: number;
  app: string;
  server_url: string;
  username: string;
  password: string;
  /** Gateway API key (x-api-key auth) — optional alternative to password */
  api_key?: string;
  mode: 'http_rest' | 'smpp_inbound';
  smpp_host?: string;
  smpp_port?: number;
  device_name?: string;
}

interface Props {
  onPaired: (config: Partial<GatewayConfig>) => void;
  onCancel: () => void;
}

/**
 * Full-screen camera QR scanner. Scans the server-generated pairing code and
 * converts it into a GatewayConfig — no manual IP/username/password typing.
 */
export const QrPairingScanner: React.FC<Props> = ({ onPaired, onCancel }) => {
  const scannerRef = useRef<Html5Qrcode | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [starting, setStarting] = useState(true);
  const handledRef = useRef(false);

  useEffect(() => {
    const scanner = new Html5Qrcode('qr-reader-region', { verbose: false });
    scannerRef.current = scanner;

    const onScan = (decodedText: string) => {
      if (handledRef.current) return;
      handledRef.current = true;
      try {
        const payload = JSON.parse(decodedText) as PairingPayload;
        if (payload.app !== 'net2apppro' || !payload.server_url || !payload.username) {
          setError('This QR is not a Net2appPro pairing code');
          handledRef.current = false;
          return;
        }
        const host = payload.server_url.replace(/^https?:\/\//, '').replace(/[:/].*$/, '');
        onPaired({
          serverUrl: payload.server_url,
          username: payload.username,
          password: payload.password || '',
          apiKey: payload.api_key || '',
          connectionType: payload.mode === 'smpp_inbound' ? 'smpp_inbound' : 'http_rest',
          smppHost: payload.smpp_host || host,
          smppPort: payload.smpp_port || 2775,
          deviceName: payload.device_name || payload.username,
        });
      } catch {
        setError('Invalid QR content');
        handledRef.current = false;
      }
    };

    const cameraCfg = { facingMode: 'environment' as const };
    scanner
      .start(
        cameraCfg,
        { fps: 10, qrbox: { width: 240, height: 240 } },
        onScan,
        () => { /* per-frame decode miss — ignore */ }
      )
      .then(() => setStarting(false))
      .catch((e) => {
        setStarting(false);
        setError('Camera unavailable: ' + (e?.message || e));
      });

    return () => {
      scanner.stop().then(() => scanner.clear()).catch(() => {});
    };
  }, [onPaired]);

  return (
    <div className="qr-scan-overlay">
      <div className="qr-scan-box">
        <h2>📷 Scan Pairing QR</h2>
        <p className="qr-scan-hint">
          In the NET2APP Hub web UI: Suppliers → choose the Android device → <b>Pairing QR</b>
        </p>
        <div id="qr-reader-region" className="qr-reader" />
        {starting && <p className="qr-scan-status">Starting camera…</p>}
        {error && <p className="qr-scan-status qr-error">{error}</p>}
        <button className="btn btn-secondary" onClick={onCancel}>✖ Cancel</button>
      </div>
    </div>
  );
};
