#!/bin/bash
# ============================================================================
# NET2APP Hub — Tailscale + 3proxy Residential Proxy Node Setup
# ============================================================================
# Downloads and configures Tailscale + 3proxy on Ubuntu/Debian.
# After running, this machine becomes a SOCKS5 proxy node on your Tailscale
# mesh — OTT devices (WhatsApp/Telegram) route through it for residential IPs.
#
# Usage:
#   curl -sSL http://YOUR_SERVER:3001/api/ott/proxy/setup-script | sudo bash
#
#   Or with auth key:
#   curl -sSL ... | sudo TS_AUTHKEY=tskey-client-xxx bash
# ============================================================================

set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }

echo ""
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║   NET2APP Hub — Proxy Node Setup            ║"
echo "  ║   Tailscale + 3proxy Residential Proxy      ║"
echo "  ╚══════════════════════════════════════════════╝"
echo ""

# ── Check root ──
[ "$(id -u)" -eq 0 ] || err "Run as root: sudo bash $0"

# ── Detect OS ──
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
else
    err "Cannot detect OS. Ubuntu/Debian required."
fi

case $OS in
    ubuntu|debian) log "Detected: $OS $VERSION_ID" ;;
    *) warn "Untested OS: $OS. Proceeding anyway..." ;;
esac

# ═══════════════════════════════════════════════════════════════
# 1. INSTALL TAILSCALE
# ═══════════════════════════════════════════════════════════════
if ! command -v tailscale &>/dev/null; then
    log "Installing Tailscale..."
    curl -fsSL https://tailscale.com/install.sh | sh
    log "Tailscale installed: $(tailscale version | head -1)"
else
    log "Tailscale already installed: $(tailscale version | head -1)"
fi

# ── Authenticate Tailscale ──
if tailscale status &>/dev/null; then
    log "Tailscale already authenticated — mesh active"
elif [ -n "$TS_AUTHKEY" ]; then
    log "Authenticating Tailscale with auth key..."
    tailscale up --authkey="$TS_AUTHKEY" --accept-routes --accept-dns=false
    log "Tailscale connected! IP: $(tailscale ip -4 2>/dev/null || echo 'pending')"
else
    warn "No TS_AUTHKEY provided."
    echo ""
    echo "  Option 1: Re-run with auth key:"
    echo "    curl ... | sudo TS_AUTHKEY=tskey-client-xxx bash"
    echo ""
    echo "  Option 2: Login interactively:"
    echo "    sudo tailscale up"
    echo ""
    echo "  Then re-run this script to finish 3proxy setup."
    echo ""
fi

# ═══════════════════════════════════════════════════════════════
# 2. INSTALL 3PROXY (SOCKS5)
# ═══════════════════════════════════════════════════════════════
PROXY_PORT="${PROXY_PORT:-3128}"
PROXY_USER="${PROXY_USER:-}"
PROXY_PASS="${PROXY_PASS:-}"

if ! command -v 3proxy &>/dev/null; then
    log "Installing 3proxy..."
    apt-get update -qq
    apt-get install -y -qq 3proxy
    log "3proxy installed"
else
    log "3proxy already installed"
fi

# ── Configure 3proxy ──
CONF_DIR="/etc/3proxy"
CONF_FILE="$CONF_DIR/3proxy.cfg"
mkdir -p "$CONF_DIR"

cat > "$CONF_FILE" << '3PROXY_EOF'
# NET2APP Hub — 3proxy SOCKS5 Residential Proxy Configuration
# Auto-generated by setup-tailscale-3proxy.sh
# DO NOT EDIT MANUALLY — re-run the setup script to update.

nscache 65536
nserver 8.8.8.8
nserver 1.1.1.1
timeouts 1 5 30 60 180 1800 15 60
log /var/log/3proxy/3proxy.log D
rotate 7

# Allow connections from Tailscale mesh (100.x.x.x) and localhost
allow * 127.0.0.1,100.0.0.0/8

# Anonymous SOCKS5 proxy — no auth
auth none
socks -p3128
flush
3PROXY_EOF

# Add auth if credentials provided
if [ -n "$PROXY_USER" ] && [ -n "$PROXY_PASS" ]; then
    log "Configuring SOCKS5 with authentication: $PROXY_USER"
    sed -i 's/auth none/auth strong/' "$CONF_FILE"
    echo "users $PROXY_USER:CL:$PROXY_PASS" >> "$CONF_FILE"
fi

mkdir -p /var/log/3proxy
touch /var/log/3proxy/3proxy.log

# ── Systemd service for 3proxy ──
cat > /etc/systemd/system/3proxy.service << 'SYSTEMD_EOF'
[Unit]
Description=3proxy SOCKS5 Proxy
After=network.target tailscaled.service
Wants=tailscaled.service

[Service]
Type=simple
ExecStart=/usr/bin/3proxy /etc/3proxy/3proxy.cfg
Restart=always
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
SYSTEMD_EOF

systemctl daemon-reload
systemctl enable 3proxy --now
log "3proxy started on port $PROXY_PORT (SOCKS5)"

# ═══════════════════════════════════════════════════════════════
# 3. OPEN FIREWALL (UFW/iptables)
# ═══════════════════════════════════════════════════════════════
# 3proxy listens on all interfaces — Tailscale (100.x.x.x) is the primary
# access path. For direct IP access, open the port.
if command -v ufw &>/dev/null && ufw status | grep -q "Status: active"; then
    ufw allow from 100.0.0.0/8 to any port $PROXY_PORT proto tcp 2>/dev/null || true
    log "UFW: allowed Tailscale mesh (100.0.0.0/8) on port $PROXY_PORT"
fi

# ═══════════════════════════════════════════════════════════════
# 4. VERIFY
# ═══════════════════════════════════════════════════════════════
TS_IP=$(tailscale ip -4 2>/dev/null || echo "unknown")
echo ""
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║   ✅ Setup Complete!                         ║"
echo "  ╠══════════════════════════════════════════════╣"
echo "  ║   Tailscale IP : $TS_IP"
echo "  ║   SOCKS5 Port  : $PROXY_PORT"
echo "  ║   Proxy Addr   : $TS_IP:$PROXY_PORT"
echo "  ╠══════════════════════════════════════════════╣"
echo "  ║   Add this node to NET2APP Hub:              ║"
echo "  ║   OTT Devices → Proxy Pool → Add             ║"
echo "  ║   Enter: $TS_IP:$PROXY_PORT"
echo "  ╚══════════════════════════════════════════════╝"
echo ""

# Test SOCKS5 locally
if command -v nc &>/dev/null; then
    if echo -en '\x05\x01\x00' | nc -w 2 127.0.0.1 $PROXY_PORT | xxd -p | grep -q '0500'; then
        log "SOCKS5 proxy responding on localhost:$PROXY_PORT"
    else
        warn "SOCKS5 proxy test inconclusive — check logs: journalctl -u 3proxy"
    fi
fi

exit 0
